name: Immobilier watcher


on:

  schedule:

    - cron: "*/10 * * * *"

  workflow_dispatch:



jobs:

  search:


    runs-on: ubuntu-latest


    steps:


      - name: Checkout
        uses: actions/checkout@v4



      - name: Restore database cache
        uses: actions/cache@v4

        with:

          path: storage/database.db

          key: immobilier-database-${{ github.run_id }}

          restore-keys: |
            immobilier-database-



      - name: Python setup

        uses: actions/setup-python@v5

        with:

          python-version: "3.12"



      - name: Install dependencies

        run:

          pip install -r requirements.txt



      - name: Run watcher

        env:

          DISCORD_WEBHOOK:
            ${{ secrets.DISCORD_WEBHOOK }}

        run:

          python main.py